history/urls.py
"""Defines URL patterns for History App - portfolio"""
from django.urls import path
from . import views

app_name = "history"
urlpatterns = [
    # A page for viewing education history details
    path("my_education/", views.my_education, name="my_education"),
    # A page for viewing work experience 
    path("work_experience/", views.work_experience, name="work_experience"), 
    # A page for viewing skills 
    path("skills/", views.skills, name="skills"), 
    # About me page with hobbies 
    path("about/", views.about, name="about"), 
]

portfolio/urls.py
"""Defines URL patterns for portfolio"""
from django.urls import path 
from . import views 

app_name = "portfolio" 
urlpatterns = [
    # Home page 
    path("", views.index, name="index"), 
    # A page for viewing featured projects 
    path("projects/", views.projects, name="projects"), 
    # A path to generate a pdf of project 
    path("<int:project_id>/print/", views.print_project, name="print_project"), 
    # A page to view a single project 
    path("<int:project_id>/", views.project, name="project"), 
    # A page to add a new project 
    path("<int:project_id>/add_new_project/", views.add_new_project, name="add_new_project"),
]

portfolio/models.py
from django.db import models

# Porfolio App Models


class Project(models.Model):
    """A model representing projects within my portfolio"""

    git_repo = models.URLField(max_length=300, blank=True)
    title = models.CharField(max_length=250, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    created_with = models.CharField(max_length=400)
    description = models.CharField(max_length=400)

    def __str__(self) -> str:
        """return a string representation of Project model"""
        title = self.title.title()
        repo = self.git_repo
        return f"{title} | {repo}"


class Profile(models.Model):
    """a model representing my resume profile"""

    name = models.CharField(max_length=50)
    text = models.TextField()

    def __str__(self) -> str:
        """return a string representation of Profile model"""
        profile_name = self.name.title()
        text = self.text
        id = self.id 
        return f"{id} - {profile_name} | {text[:50]}..."


class MyLinks(models.Model):
    """a model representing my resume important links"""

    name = models.CharField(max_length=125)
    url = models.URLField(max_length=300)

    class Meta:
        verbose_name_plural = "mylinks"

    def __str__(self) -> str:
        """return a string representation of MyLinks"""
        name = self.name.title()
        url = self.url
        return f"{name} | {url}"

portfolio/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    """
    A Form for adding new Projects
    """

    class Meta:
        model = Project
        fields = [
            "git_repo",
            "title",
            "created_with",
            "description",
        ]
        labels = {
            "git_repo": "Github Repo",
            "title": "Title",
            "created_with": "Created Using",
            "description": "Description",
        }

portfolio/views.py
from django.shortcuts import render, redirect
from .models import MyLinks
from .models import Project
from .forms import ProjectForm
import datetime

# Imports for using ReportLab for PDF gen
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet


def index(request):
    """the home page for my portfolio app"""
    links = MyLinks.objects.all()
    context = {"links": links}
    return render(request, "portfolio/index.html", context)


def projects(request):
    """A page for viewing current featured projects"""
    projects = Project.objects.all()
    context = {"projects": projects}
    return render(request, "portfolio/projects.html", context)


def print_project(request, project_id):
    # Need to add a view for viewing projects - view all in list with view/print options
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    project = Project.objects.get(id=project_id)
    repo = project.git_repo
    title = project.title
    date = project.date_added  # use .strftime('%m/%d/%Y')
    created_with = project.created_with
    description = project.description
    project_id = project.id

    logo = "./static/img/dg.jpg"
    p.drawImage(logo, 216, 576, width=None, height=None)

    title_obj = p.beginText(270, 504)
    title_obj.setFont("Helvetica-Oblique", 14, leading=None)
    title_obj.textLine(text=f"{title.title()}")
    p.drawText(title_obj)

    date_obj = p.beginText(504, 468)
    date_obj.setFont("Helvetica", 11, leading=None)
    date_obj.textLine(text=f"{date.strftime('%m/%d/%Y')}")
    p.drawText(date_obj)

    create_obj = p.beginText(54, 400)
    create_obj.setFont("Helvetica", 10, leading=None)
    create_obj.textLine(text=f"Created using: {created_with}")
    p.drawText(create_obj)

    des_obj = p.beginText(54, 328)
    des_obj.setFont("Helvetica", 11, leading=None)
    des_obj.textLine(text=f"{description[:100]}")
    p.drawText(des_obj)

    des2_obj = p.beginText(72, 310)
    des2_obj.setFont("Helvetica", 11, leading=None)
    des2_obj.textLine(text=f"{description[100:]}")
    p.drawText(des2_obj)

    repo_obj = p.beginText(72, 256)
    repo_obj.setFont("Helvetica", 11, leading=None)
    repo_obj.textLine(text=f"{repo}")
    p.drawText(repo_obj)

    p.showPage()
    p.save()

    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename=f"project{project_id}.pdf")


def project(request, project_id):
    """a page for viewing the details of a single project"""
    project = Project.objects.get(id=project_id)
    if project.title.lower() == "photo blog":
        url = "https://github.com/dannynow6/dg-photo"
    elif project.title.lower() == "adventure game":
        url = "https://github.com/dannynow6/adventure-game-v2"
    elif project.title.lower() == "podcast app":
        url = "https://github.com/dannynow6/esp-kivy-project"
    context = {"project": project, "url": url}
    return render(request, "portfolio/project.html", context)


def add_new_project(request, project_id):
    """A page for adding a new project"""
    old_project = Project.objects.get(id=project_id)
    gitrepo = old_project.git_repo
    old_title = old_project.title
    created_using = old_project.created_with
    describe = old_project.description
    old_project_data = {
        "git_repo": gitrepo,
        "title": old_title,
        "created_with": created_using,
        "description": describe,
    }

    if request.method != "POST":
        # Initial request; pre-fill form with project data
        form = ProjectForm(initial=old_project_data)
    else:
        # POST data submitted and process data
        form = ProjectForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("portfolio:projects")
    context = {"form": form}
    return render(request, "portfolio/add_new_project.html", context)

portfolio/templates/portfolio/add_new_project.html
{% extends "portfolio/base.html" %} {% load static %}
{% block title %}Add New Project Form{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a class="my-navs" href="{% url 'portfolio:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a class="my-navs" href="{% url 'portfolio:projects' %}">Projects</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add New Project</li>
    </ol>
</nav>
<div class="container w-75 p-4 my-4 border">
    <h3 class="text-secondary p-4 border-bottom" style="background-color: #f2fbff;">New Project</h3>
    <div class="container p-4 my-2">
      <form action="{% url 'portfolio:add_new_project' project.id %}" method="POST">
      {% csrf_token %} 
      <p>
        {{ form.as_p }}
      </p>
        <button
          type="submit"
          class="btn btn-lg btn-outline-primary"
          role="button"
          alt="submit"
          value="Save"
        >
          Save New Project
        </button>
      </form>
    </div>
  </div>
{% endblock content %}

portfolio/templates/portfolio/base.html
{% load static %} {% load bootstrap4 %} {% load bootstrap_icons %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="author" content="Daniel Garro" />
        <title>{% block title %}Daniel Garro Profile{% endblock title %}</title>
        {% bootstrap_css %} {% bootstrap_javascript jquery='full' %} 
        <!-- My stylesheet -->
        <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
    </head>
    <body class="m-3" id="main-bg-img">
        <nav class="navbar navbar-expand-lg navbar-light shadow-lg p-3 mb-5 bg-white rounded">
            <a class="navbar-brand" href="{% url 'portfolio:index' %}">
              <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top">
              Profile | Daniel Garro 
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'portfolio:index' %}">{% bs_icon 'house' %} Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'portfolio:projects' %}">{% bs_icon 'file-code' %} Projects</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'history:work_experience' %}">{% bs_icon 'file-person' %} Work Experience</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'history:my_education' %}">{% bs_icon 'mortarboard' %} Education</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'history:skills' %}">{% bs_icon 'card-checklist' %} Skills</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'history:about' %}">{% bs_icon 'info-circle' %} About</a>
                    </li>
                </ul>
            </div>
        </nav>
        <main>
            {% block content %}{% endblock content %}
            <br />
            <div class="container w-75">
                <footer class="text-center text-dark border-top border-muted pt-3">
                    <img src="{% static 'img/logo.png' %}" width="25" height="25" class="d-inline-block"> &copy; Daniel Garro 2023 
                </footer>
            </div>
        </main>
    </body>
</html>

portfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %} {% load static %} {% load bootstrap_icons %}
{% block title %}Daniel Garro Profile Home{% endblock title %}
{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-white">
            <li class="breadcrumb-item active" aria-current="page">Home</li>
        </ol>
    </nav>
    <div class="container" id="main-title-cont">
        <div class="shadow-lg p-4 m-3">
            <article class="border-bottom border-muted">
                <h2 class="text-secondary text-center display-4">
                    <img src="{% static 'img/logo.png' %}" width="55" height="55">
                    <a class="my-navs-title" href="{% url 'portfolio:index' %}">Profile | Daniel Garro</a> 
                </h2>
            </article>
        </div>
    </div>
    <div class="container w-75">
        <h5 class="text-muted text-right pr-3"><a class="my-navs" href="{% url 'portfolio:projects' %}">Projects</a><h5>
        <br />
        <h5 class="text-muted text-right pr-3"><a class="my-navs" href="{% url 'history:work_experience' %}">Work Experience</a></h5>
        <br />
        <h5 class="text-muted text-right pr-3"><a class="my-navs" href="{% url 'history:my_education' %}">Education</a></h5>
        <br />
        <h5 class="text-muted text-right pr-3"><a class="my-navs" href="{% url 'history:skills' %}">Skills</a></h5>
        <br />
        <h5 class="text-muted text-right pr-3"><a class="my-navs" href="{% url 'history:about' %}">About</a></h5>
        {% for link in links %}
            <br />
            <h5 class="text-muted text-right pr-3"><a class="my-navs" href="{{ link.url }}" target="_blank">
                {% if link.name == 'GitHub' %}
                {% bs_icon 'github' %} 
                {% else %}
                {% bs_icon 'linkedin' %}
                {% endif %}
                {{ link.name }}</a></h5>
        {% endfor %}
    </div>
   
{% endblock content %}

portfolio/templates/portfolio/project.html
{% extends "portfolio/base.html" %} {% load static %} {% load bootstrap_icons %}
{% block title %}{{ project.title|title }} Project{% endblock title %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a class="my-navs" href="{% url 'portfolio:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a class="my-navs" href="{% url 'portfolio:projects' %}">Projects</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ project.title|title }}</li>
    </ol>
</nav>
    <div class="container w-75 border-bottom border-muted">
        <h4 class="text-center text-secondary display-4"><a class="my-navs-title" href="{% url 'portfolio:projects' %}">{{ project.title|title }}</a></h4>
        <br />
    </div>
    <div class="container w-75">
        <article class="text-secondary text-center">
            <p class="mt-4">{{ project.created_with }}</p>
            <br /> 
            <p>{{ project.description }}</p>
            <br />
            <a class="my-navs" href="{{ url }}">{% bs_icon 'github' %}</a>
            <br /> 
            <a class="my-navs" href="{% url 'portfolio:print_project' project.id %}">{% bs_icon 'printer' %}</a>
            <br />
            <a class="my-navs" href="{% url 'portfolio:add_new_project' project.id %}">{% bs_icon 'file-plus' %}</a>
        </article>
    </div>
{% endblock content %}

portfolio/templates/portfolio/projects.html
{% extends "portfolio/base.html" %} {% load static %} {% load bootstrap_icons %}
{% block title %}Daniel Garro's Projects{% endblock title %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a class="my-navs" href="{% url 'portfolio:index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Projects</li>
    </ol>
</nav>
<div class="container">
    <div class="shadow-lg p-4 m-3">
        <article class="border-bottom border-muted">
            <h2 class="text-secondary text-center display-4">
                <img src="{% static 'img/logo.png' %}" width="55" height="55">
                <a class="my-navs-title" href="{% url 'portfolio:index' %}">Projects | Daniel Garro</a> 
            </h2>
        </article>
    </div>
</div>
<div class="container w-75 mt-4">
    <ul class="list-group">
        {% for project in projects %} 
        <li class="list-group-item">
            <article>
                <h6 class="text-secondary">{{ project.title|title }}</h6>
                <br />
                <p class="text-secondary">{{ project.description }}</p>
                <a class="my-navs" href="{% url 'portfolio:project' project.id %}">{% bs_icon 'link' size='1.5em' %}</a>
            </article>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}